version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      APP_NAME: CRUDApp
      DB_URL: jdbc:postgresql://db:5432/crud_db
      DB_USERNAME: crud_user
      DB_PASSWORD: crud_password
      HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: crud_db
      POSTGRES_USER: crud_user
      POSTGRES_PASSWORD: crud_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
